config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions" }
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  resources :users

  get '/enable_auto_advance_after_vote', to: 'edits#enable_auto_advance_after_vote'
  get '/disable_auto_advance_after_vote', to: 'edits#disable_auto_advance_after_vote'
  get '/enable_auto_advance_after_save', to: 'edits#enable_auto_advance_after_save'
  get '/disable_auto_advance_after_save', to: 'edits#disable_auto_advance_after_save'

  root 'pages#home'

  get '/help', to: 'pages#help'
  get '/about', to: 'pages#about'
  get '/timeout', to: 'pages#timeout'

  resources :messages do
    resources :translations
  end
  get '/all_translations', to: 'translations#all_translations'

  resources :translations do
    resources :sentences
    member do
      get :import_lookup_form
      post :import_lookup
      get :randomize_translate_contributions
    end
  end
  get '/destroy_sentences', to: 'translations#destroy_sentences'
  get '/destroy_lookups', to: 'translations#destroy_lookups'

  resources :lookups

  resources :sentences do
    resources :edits do
      member do
        post :vote
      end
    end
    member do
      get :next
      get :prev
      get :increase_context
      get :decrease_context
      get :timeout
      get :multi_button_action
      get :show_search
      get :show_preview
    end
  end

  
  resources :assignments do
    member do
      get :import_content_form
      post :import_content
      get :validate_content_form
      post :validate_content
      get :report
    end
  end
  get '/destroy_contributions', to: 'assignments#destroy_contributions'
  get '/status_assignments', to: 'assignments#status_assignments'
  get '/status_assignments_seven_day', to: 'assignments#status_assignments_seven_day'
  get '/status_assignments_all_time_work', to: 'assignments#status_assignments_all_time_work'
  get '/status_assignments_all_time_translations', to: 'assignments#status_assignments_all_time_translations'
  get '/team_assignments', to: 'assignments#team_assignments'

  resources :contributions

  post '/sentences/:sentence_id/edits/:id/save_modified_clone', :to => 'edits#save_modified_clone'

  get '/users/:id/assignments/:id/switch', to: 'users#switch_current_assignment'

  resources :text_exports, :only => [:new, :create]

  resources :dash_exports, :only => [:new, :create]

end

app/models/message.rb
#class Message < ActiveRecord::Base
class Message < ApplicationRecord
  has_many :translations
  # before_save { self.tod = tod.downcase, self.dow = dow.downcase } handled in template - only submits correct form
  validates :dod, presence: true
  validates :tod, presence: true, inclusion: { in: %w(s b x y z),
    message: "%{value} is not a valid time of day. Use one of: s b x y z" }
  validates :dow, presence: true, inclusion: { in: %w(su mo tu we th fr sa),
    message: "%{value} is not a valid day of week. Use one of: su mo tu we th fr sa" }
  validates :title, presence: true, length: { minimum: 1, maximum: 64 }

  def message_text
    "#{dod}#{tod} #{title}"
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]
  before_action :require_admin

  # GET /messages
  # GET /messages.json
  def index
    #@messages = Message.all
    @messages = Message.all.order('descriptor')
    #@messages = Message.paginate(page: params[:page], per_page: 10)
    #@messages = Message.order('dod').(paginate(page: params[:page], per_page: 10)
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:dod, :tod, :dow, :descriptor, :title)
    end

    def require_admin
      if !user_signed_in? || (user_signed_in? and !current_user.admin?)
        flash[:danger] = 'Only admins can perform that action'
        redirect_to root_path
      end
    end
    
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= render 'shared/errors', obj: [@message] %>
<div class='row'>
  <div class='col-xs-12'>
    <%= form_for(@message, :html => {class: 'form-horizontal', role: 'form'}) do |f| %>
      <div class='form-group'>
        <div class='control-label col-sm-2'>
          <%= f.label 'Date Of Delivery' %>
        </div>
        <div class='col-sm-8'>
          <%= f.date_select :dod, start_year: 1947, end_year: 1965, class: 'form-control', autofocus: true %>
        </div>
      </div>
      <div class='form-group'>
        <div class='control-label col-sm-2'>
          <%= f.label 'Time Of Day' %>
        </div>
        <div class='col-sm-8'>
          <%= f.select :tod, [['Breakfast', 'b'], ['Sunrise', 's'], ['Morning', 'x'], ['Afternoon', 'y'], ['Evening', 'z']], class: 'form-control', placeholder: 'Time Of Day' %>
        </div>
      </div>
      <div class='form-group'>
        <div class='control-label col-sm-2'>
          <%= f.label 'Day Of Week' %>
        </div>
        <div class='col-sm-8'>
          <%= f.select :dow, [['Sunday', 'su'], ['Monday', 'mo'], ['Tuesday', 'tu'], ['Wednesday', 'we'], ['Thursday', 'th'], ['Friday', 'fr'], ['Saturday', 'sa']], class: 'form-control', placeholder: 'Day Of Week' %>
        </div>
      </div>
      <div class='form-group'>
        <div class='control-label col-sm-2'>
          <%= f.label 'Descriptor' %>
        </div>
        <div class='col-sm-8'>
          <%= f.text_field :descriptor, class: 'form-control', placeholder: 'Descriptor' %>
        </div>
      </div>
      <div class='form-group'>
        <div class='control-label col-sm-2'>
          <%= f.label 'Title' %>
        </div>
        <div class='col-sm-8'>
          <%= f.text_field :title, class: 'form-control', placeholder: 'Title' %>
        </div>
      </div>
      <div class="form-group">
        <div class='col-sm-offset-2 col-xs-10'>
          <%= f.submit class: 'btn btn-primary btn-lg' %>
        </div>
      </div>
    <% end %>
    <div class='col-xs-4 col-xs-offset-4'>
      [ <%= link_to "Cancel request and return to messages listing", messages_path %> ]
    </div>
  </div>
</div>

app/views/messages/edit.html.erb
<h1 align='center'>Editing Message</h1>

<%= render 'form' %>

app/views/messages/index.html.erb
<div class='container'>
  <h1 align='center'>All Messages</h1>
  <!--
  <div align='center'>
    <%#= will_paginate @messages %>
  </div>
  -->
  <table class='table table-condensed table-bordered table-hover'>
    <thead>
      <tr>
        <th>Id</th>
        <th>Date</th>
        <th>Time</th>
        <th>Day</th>
        <th>Title</th>
        <th colspan="2">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @messages.each do |message| %>
        <tr>
          <td><%= link_to message.id, message %></td>
          <td><%= message.dod %></td>
          <td><%= message.tod %></td>
          <td><%= message.dow %></td>
          <td><%= message.title %></td>
          <td><%= link_to 'Edit', edit_message_path(message) %></td>
          <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <!--
  <div align='center'>
    <%#= will_paginate @messages %>
  </div>
  -->
</div>

app/views/messages/new.html.erb
<h1 align='center'>New Message</h1>

<%= render 'form' %>

app/views/messages/show.html.erb
<h2 align='center'>Message</h2>

<div class='col-xs-8 col-xs-offset-2'>

  <table class='table table-striped'>
    <tbody>
      <tr>
        <td><strong>Id</strong></td>
        <td><%= @message.id %></td>
      </tr>
      <tr>
        <td><strong>Date Of Delivery</strong></td>
        <td><%= @message.dod %></td>
      </tr>
      <tr>
        <td><strong>Time Of Day</strong></td>
        <td><%= @message.tod %></td>        
      </tr>
      <tr>
        <td><strong>Day Of Week</strong></td>
        <td><%= @message.dow %></td>
      </tr>
      <tr>
        <td><strong>Descriptor</strong></td>
        <td><%= @message.descriptor %></td>
      </tr>
      <tr>
        <td><strong>Title</strong></td>
        <td><%= @message.title %></td>
      </tr>
    </tbody>
  </table>

  <div class='show-actions'>
    <%= link_to 'Edit', edit_message_path(@message), class: 'btn btn-xs btn-primary' %>
    <%= link_to 'Delete', message_path(@message), method: :delete, data: { confirm: 'Are you sure you want to delete the message?'}, class: 'btn btn-xs btn-danger' %>
    <%= link_to 'View all Messages', messages_path, class: 'btn btn-xs btn-success' %>
    <%= link_to 'New Message', new_message_path, class: 'btn btn-xs btn-primary' %>
    &nbsp;
    <%= link_to 'New Translation', new_message_translation_path(@message), class: 'btn btn-xs btn-primary' %>
  </div>

  <div>
    <h3 align='center'>Translations</h3>
    <table class='table table-striped table-condensed'>
      <thead>
	<tr>
          <td><strong>id</strong></td>
          <td><strong>lan</strong></td>
          <td><strong>tran_title</strong></td>
          <td><strong>version</strong></td>
          <td><strong>blkc</strong></td>
          <td><strong>subc</strong></td>
          <td><strong>senc</strong></td>
          <td><strong>xcrip</strong></td>
          <td><strong>li</strong></td>
        </tr>
      </thead>
      <tbody>
<%# @translation.assignments.each do |a| %>
<% @message.translations.each do |t| %>
	<tr>
          <td><%= link_to t.id, message_translation_path(t.message, t) %></td>
          <td><%= t.lan %></td>
          <td><%= t.tran_title %></td> 
          <td><%= t.version %></td> 
          <td><%= t.blkc %></td>
          <td><%= t.subc %></td>
          <td><%= t.senc %></td>
          <td><%= t.xcrip %></td>
          <td><%= t.li %></td>
	  <td><%= link_to 'Edit', edit_message_translation_path(t.message, t) %></td>
	  <td><%= link_to 'Delete', t, method: :delete, data: { confirm: 'Are you sure you want to delete this Translation?' } %></td>
        </tr> 
<% end %>
      </tbody>
    </table>
  </div>  

</div>