config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions" }
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  resources :users

  get '/enable_auto_advance_after_vote', to: 'edits#enable_auto_advance_after_vote'
  get '/disable_auto_advance_after_vote', to: 'edits#disable_auto_advance_after_vote'
  get '/enable_auto_advance_after_save', to: 'edits#enable_auto_advance_after_save'
  get '/disable_auto_advance_after_save', to: 'edits#disable_auto_advance_after_save'

  root 'pages#home'

  get '/help', to: 'pages#help'
  get '/about', to: 'pages#about'
  get '/timeout', to: 'pages#timeout'

  resources :messages do
    resources :translations
  end
  get '/all_translations', to: 'translations#all_translations'

  resources :translations do
    resources :sentences
    member do
      get :import_lookup_form
      post :import_lookup
      get :randomize_translate_contributions
    end
  end
  get '/destroy_sentences', to: 'translations#destroy_sentences'
  get '/destroy_lookups', to: 'translations#destroy_lookups'

  resources :lookups

  resources :sentences do
    resources :edits do
      member do
        post :vote
      end
    end
    member do
      get :next
      get :prev
      get :increase_context
      get :decrease_context
      get :timeout
      get :multi_button_action
      get :show_search
      get :show_preview
    end
  end

  
  resources :assignments do
    member do
      get :import_content_form
      post :import_content
      get :validate_content_form
      post :validate_content
      get :report
    end
  end
  get '/destroy_contributions', to: 'assignments#destroy_contributions'
  get '/status_assignments', to: 'assignments#status_assignments'
  get '/status_assignments_seven_day', to: 'assignments#status_assignments_seven_day'
  get '/status_assignments_all_time_work', to: 'assignments#status_assignments_all_time_work'
  get '/status_assignments_all_time_translations', to: 'assignments#status_assignments_all_time_translations'
  get '/team_assignments', to: 'assignments#team_assignments'

  resources :contributions

  post '/sentences/:sentence_id/edits/:id/save_modified_clone', :to => 'edits#save_modified_clone'

  get '/users/:id/assignments/:id/switch', to: 'users#switch_current_assignment'

  resources :text_exports, :only => [:new, :create]

  resources :dash_exports, :only => [:new, :create]

end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  #before_filter :get_translation, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  #before_filter :get_user, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  before_action :set_assignment, only: [:show, :edit, :update, :destroy]
  #before_action :require_admin
  before_action :require_admin, except: [:report, :team_assignments]
  ##before_action :require_team_report_authorization, only: [:team_assignments]
  #before_action :require_authorization

  helper_method :assignment_vote_time
  helper_method :assignment_create_time

  def index
    require_admin
    @assignments = Assignment.all
    #@assignments = @translation.assignments
  end

  def status_assignments
    require_admin
    @time_now = Time.now
    #@time_now = Time.new(2017, 8, 31, 0, 0, 0)
    @time_lastweek = @time_now - 7.days

    # 7-day report (uses method4, others have been deleted)
    Assignment.cleanup_report_data #needed, else complains about table existing already
    Assignment.prepare_report_data(@time_lastweek, @time_now, "('TE', 'QE', 'CE')").to_a
    @status_report = Assignment.status_report.to_a
    @status_summary = Assignment.status_summary.to_a.first
    Assignment.cleanup_report_data

    # All-Time Work report
    # TODO: move more logic out of view
    @all_users = User.all.order('username')
    
    # All-Time Translations report
    # TODO: move more logic out of view
    @TE_completed_LA_assignments = Assignment.te_completed_la_assignments()
  end

  def status_assignments_seven_day
    require_admin
    @time_now = Time.now
    #@time_now = Time.new(2017, 8, 31, 0, 0, 0)
    @time_lastweek = @time_now - 7.days

    # 7-day report (uses method4, others have been deleted)
    Assignment.cleanup_report_data #needed, else complains about table existing already
    Assignment.prepare_report_data(@time_lastweek, @time_now, "('TE', 'QE', 'CE')").to_a
    @status_report = Assignment.status_report.to_a
    @status_summary = Assignment.status_summary.to_a.first
    Assignment.cleanup_report_data
  end

  def status_assignments_all_time_work
    require_admin

    # All-Time Work report
    # TODO: move more logic out of view
    @all_users = User.all.order('username')
  end

  def status_assignments_all_time_translations
    require_admin

    # All-Time Translations report
    # TODO: move more logic out of view
    @TE_completed_LA_assignments = Assignment.te_completed_la_assignments()
  end

  def team_assignments
    require_team_report_authorization

    @time_now = Time.now
    #@time_now = Time.new(2017, 8, 31, 0, 0, 0)
    @time_lastweek = @time_now - 7.days

    Assignment.cleanup_report_data #needed, else complains about table existing already
    Assignment.prepare_report_data(@time_lastweek, @time_now, "('TE', 'QE', 'CE')").to_a
    @team_report = Assignment.team_report(current_user.cur_assign.translation.lan).to_a
    @team_summary = Assignment.team_summary(current_user.cur_assign.translation.lan).to_a.first
    Assignment.cleanup_report_data
  end

  def show
    #require_authorization
  end

  def new
    @assignment = Assignment.new(place: 1)
  end

  def edit
  end

  def create
    #get_translation #won't work here
    @assignment = Assignment.new(assignment_params)
    #@translation.assignments << @assignment
    #@user.assignments << @assignment

    if @assignment.save
      flash[:success] = 'Assignment was successfully created.'

      #set user's cur_assign to this newly-created assignment so that a user always have a cur_assign
      #NO: else cur_assign will become nil for each new asn created!
      #@user = User.find(assignment_params[:user_id])
      #@user.cur_assign = @assignment
      #@user.save

      #get_translation #won't work here
      redirect_to assignment_path(@assignment)
      #redirect_to message_translation_path(@translation.message, @translation) 
    else
      render :new
    end
  end

  def editor_complete?(role, from_status, to_status)
    (['TE','CE','QE'].include? role) && (from_status=="ip") && (to_status=="cd") #ip to cd
  end
  def pretranslator_complete?(role, from_status, to_status)
    (['MT','HT','NT'].include? role) && (from_status=="ip") && (to_status=="cd") #ip to cd
  end
  def la_complete?(role, from_status, to_status)
    (['LA'].include? role) && (from_status=="pg") && (to_status=="pd") #pg to pd
  end
  def update
    get_translation
    closeout_editor = editor_complete?(@assignment.role, @assignment.status, assignment_params[:status])
    closeout_pretranslator = pretranslator_complete?(@assignment.role, @assignment.status, assignment_params[:status])
    closeout_la = la_complete?(@assignment.role, @assignment.status, assignment_params[:status])
    closeout = closeout_editor || closeout_pretranslator || closeout_la
    if @assignment.update(assignment_params)
      if closeout
        if closeout_pretranslator
          @assignment.update(ccs: @assignment.contribution_count('T'))
	else
	  @assignment.update(ccs: @assignment.contribution_count('C'))
        end
	@assignment.update(ccs_k: @assignment.contribution_count_with_base('C', 'k'))
	@assignment.update(ccs_m: @assignment.contribution_count_with_base('C', 'm'))

	@assignment.update(vcs: @assignment.contribution_count('V'))
	@assignment.update(vcs_a: @assignment.contribution_count_with_base('V', 'a'))
	@assignment.update(vcs_c: @assignment.contribution_count_with_base('V', 'c'))
	@assignment.update(vcs_t: @assignment.contribution_count_with_base('V', 't'))
	@assignment.update(vcs_p: @assignment.contribution_count_with_base('V', 'p'))
	
	@assignment.update(ct: @assignment.create_time)
	@assignment.update(vt: @assignment.vote_time)
	
	@assignment.update(majtes: @assignment.top_edit_count('M'))
	@assignment.update(tietes: @assignment.top_edit_count('T'))
      end

      #deactivate a user's current assignment
      if @assignment.user.cur_assign    
        #this assignment is the user's cur_assign             && assignment was deactivated
        if (@assignment.id == @assignment.user.cur_assign.id) && assignment_params[:active] == "0"
          @assignment.user.update(cur_assign_id: nil) #don't want user to access a deactivated asn
        end
      end

      if closeout
        flash[:success] = 'Assignment was successfully closed out.'
      else
        flash[:success] = 'Assignment was successfully updated.'
      end
      #redirect_to message_translation_path(@translation.message, @translation) if @translation and return
      redirect_to @assignment
    else
      render :edit and return
    end
  end

  def destroy
    @translation = Translation.find(@assignment.translation.id)
    @assignment.destroy
    flash[:danger] = 'Assignment was successfully destroyed.'
    redirect_to message_translation_path(@translation.message, @translation)
  end

  def destroy_contributions
    @assignment = Assignment.find(params[:id])

    # determine the contributions to be deleted and their kind
    role = @assignment.role
    if ['MT', 'HT'].include? role
      contributions = @assignment.contributions.where("kind = 'T'")
      kind = 'T'
    elsif ['TE', 'CE', 'LA'].include? role
      #contributions = @assignment.contributions.where("kind = 'C' OR kind = 'V'")
      #kind = ['C', 'V']
      flash[:danger] = "ERROR: Deletion of contributions by the roles of TE/CE/LA is not supported"
      redirect_to assignment_path(@assignment) and return
    elsif ['EE', 'SE', 'PE'].include? role
      #contributions = @assignment.contributions.where("kind = 'C'")
      #kind = 'C'
      flash[:danger] = "ERROR: Deletion of contributions by the roles of EE/SE/PE is not supported"
      redirect_to assignment_path(@assignment) and return
    elsif ['EP'].include? role
      contributions = @assignment.contributions.where("kind = 'E'")
      kind = 'E'
    else
      flash[:danger] = "ERROR: Invalid role: #{role}"
      redirect_to assignment_path(@assignment) and return
    end

    # test if safe to delete
    num_of_contributions = contributions.length
    puts "num_of_contributions: #{num_of_contributions}"
    if num_of_contributions > 0
      contributions.each do |cont|
        cont_edit = cont.edit
	cont_edit_sentence = cont.edit.sentence

        if cont_edit.contributions.count > 1
          flash[:danger] = "ERROR: Cannot destroy edit: #{cont_edit.id}. It has other contributions pointing to it!"
          redirect_to assignment_path(@assignment) and return
        end

	if (cont_edit_sentence && cont_edit_sentence.edits.count > 1)
          flash[:danger] = "ERROR: Cannot destroy sentence: #{cont_edit_sentence.id}. It has other edits pointing to it!"
          redirect_to assignment_path(@assignment) and return
        end
      end
    end 

    # destroy
    num_of_contributions = contributions.length
    puts "num_of_contributions: #{num_of_contributions}"
    if num_of_contributions > 0
      contributions.each do |cont|
        cont_edit = cont.edit
	cont_edit_sentence = cont.edit.sentence

        cont.destroy
        cont_edit.destroy
        cont_edit_sentence.destroy if cont_edit_sentence
      end
    
      #mark as not imported 
      @assignment.update(ci: false) 

      flash[:danger] = "#{num_of_contributions} '#{kind}' contributions for this assignment deleted"
    else
      flash[:danger] = 'No contributions for this assignment deleted'
    end

    redirect_to assignment_path(@assignment)
  end

  def import_content_form
    set_assignment
    if @assignment.translation.eng_tran #import MT/HT translate content
      if @assignment.translation.eng_tran.li == false
        flash[:danger] = "ERROR: First import the ENG translation's lookup"
        redirect_to assignment_path(@assignment) and return
      end
    else #import EP English content
      if @assignment.translation.li == false
        flash[:danger] = "ERROR: First import the ENG translation's lookup"

app/helpers/assignments_helper.rb
module AssignmentsHelper
  def format_time_per_sentence(role, time, sentences)
    if ['TE', 'CE'].include? role
      '%.1f' % (time.to_f/sentences) if sentences > 0
    else
      'N/A'
    end
  end

  def format_percent_complete(role, votes, sentences)
    if ['TE', 'CE'].include? role
      '%.1f' % ((votes/sentences)*100) if sentences > 0
    else
      'N/A'
    end
  end

  def format_votes(votes)
    if !votes || votes=='0'
      ''
    else
      votes 
    end
  end

  def format_minutes(minutes)
    if !minutes || minutes=='0'
      ''
    else
      format_hours_minutes(minutes) 
    end
  end

  def format_completion(completion)
    if !completion
      ''
    elsif completion=='0'
      '0%'
    else
      #completion + '%'
      '%.1f' % completion + '%'
    end
  end

  def format_descriptor(desc)
    if desc[0] =~ /[0-9]/ #first char is a number?
      desc = desc[2..-1] #remove first 2 chars: '19'
      desc.gsub!(/b/, 'B')
      desc.gsub!(/s/, 'S')
      desc.gsub!(/x/, 'M')
      desc.gsub!(/y/, 'A')
      desc.gsub!(/z/, 'E')
    end
    desc
  end
 
  def format_hours_minutes(mins)
    hh, mm = mins.to_i.divmod(60)
    "#{hh} hours, #{mm} minutes"
  end

=begin
  def content_link()
    if @assignment.ci
      link_to 'Delete Content', { controller: 'assignments', action: 'destroy_contributions', params: {id: @assignment.id} }, data: { confirm: 'Are you sure you want to delete all contributions for this assignment?' }, class: 'btn btn-xs btn-danger'
    else
      [link_to 'Validate Content', validate_content_form_assignment_path, class: 'btn btn-xs btn-primary',   
      link_to 'Import Content', import_content_form_assignment_path, class: 'btn btn-xs btn-primary']
    end
  end      
=end

end

app/views/assignments/edit.html.erb
<h1 align='center'>Editing Assignment</h1>

<%= render 'form' %>

app/views/assignments/import_content_form.html.erb
<%#= render 'shared/errors', obj: @assignment %>

<div class='row'>
  <div class='col-xs-12'>
	  <%= form_tag({controller: "assignments", action: "import_content"}, multipart: true, :html => {class: 'form-horizontal', role: 'form'}) do %>

      <div class='form-group'>
        <div class='control-label col-sm-2'>
          <%= label_tag(:q, 'File Name') %>
        </div>
        <div class='col-sm-8'>
          <%= file_field_tag "assignment[file_name]", class: 'btn btn-primary' %>
          <!--<input type="file" id="myFile">-->
          <!-- to style: google search -- file input rails  -->
          <!--http://stackoverflow.com/questions/33028255/rails-4-how-to-apply-custom-css-to-rails-form-file-field
          http://stackoverflow.com/questions/14509449/styling-file-upload-button-for-simple-form-for-with-bootstrap-in-rails-3 -->
        </div>
      </div>

      <div class="form-group">
        <div class='col-sm-offset-2 col-xs-10'>
		<%= submit_tag('Import Content', class: 'btn btn-primary btn-lg') %>
		<%#= submit_tag('Import Content', id: "#{@assignment.id}", class: 'btn btn-primary btn-lg') %>
        </div>
      </div>      
    <% end %>

    <div class='col-xs-4 col-xs-offset-4'>
      [ <%= link_to "Cancel request and return to assignment", assignment_path %> ]
    </div>    

  </div>
</div>

app/views/assignments/new.html.erb
<h1 align='center'>New Assignment</h1>

<%= render 'form' %>

app/views/assignments/show.html.erb
<h2 align='center'>Assignment</h2>

<% #do here, else will be calculated multiple times %>
<% assign_vote_time = @assignment.vote_time %>
<% assign_create_time = @assignment.create_time %>
<% assign_total_time = assign_vote_time + assign_create_time %>
<% assign_sen_count = @assignment.sentence_count if @assignment.translation %>
<% assign_vote_contrib_count = @assignment.contribution_count('V') if @assignment.translation %>

<% m_top_edit_count = @assignment.top_edit_count('M') %>
<% t_top_edit_count = @assignment.top_edit_count('T') %>
<% z_top_edit_count = @assignment.top_edit_count('Z') %>
<% n_top_edit_count = @assignment.top_edit_count('N') %>

<% votes = @assignment.contributions.where(kind: 'V').count %>
<% sens = assign_sen_count.to_f if @assignment.translation %>

<div class='col-xs-8 col-xs-offset-2'>
  <table class='table table-striped'>
    <tbody>
      <tr>
        <td><strong>Id</strong></td>
        <td><%= @assignment.id %></td>
      </tr>
      <tr>
        <td><strong>CreatedAt</strong></td>
        <td><%= @assignment.created_at.strftime('%Y-%m-%d') %></td>
      </tr>
      <tr>
        <td><strong>Role</strong></td>
        <td><%= @assignment.role %></td>
      </tr>
      <tr>
        <td><strong>Active</strong></td>
        <td><%= @assignment.active %></td>
      </tr>
      <tr>
        <td><strong>Place</strong></td>
        <td><%= @assignment.place %></td>
      </tr>            
      <tr>
        <td><strong>Translate Contributions</strong></td>
	<td><%= @assignment.contribution_count('T') %></td>
      </tr>            
      <tr>
        <td><strong>Create Contributions</strong></td>
	<td><%= @assignment.contribution_count('C') %></td>
      </tr>            
      <tr>
        <td><strong>- by klearing</strong></td>
	<td><%= @assignment.contribution_count_with_base('C', 'k') %></td>
      </tr>            
      <tr>
        <td><strong>- by modding</strong></td>
	<td><%= @assignment.contribution_count_with_base('C', 'm') %></td>
      </tr>            
      <tr>
        <td><strong>Vote Contributions</strong></td>
	<td><%= @assignment.contribution_count('V') %></td>
      </tr>            
      <tr>
        <td><strong>- by accepting</strong></td>
	<td><%= @assignment.contribution_count_with_base('V', 'a') %></td>
      </tr>            
      <tr>
        <td><strong>- by creating</strong></td>
	<td><%= @assignment.contribution_count_with_base('V', 'c') %></td>
      </tr>            
      <tr>
        <td><strong>- by topping</strong></td>
	<td><%= @assignment.contribution_count_with_base('V', 't') %></td>
      </tr>            
      <tr>
        <td><strong>- by picking</strong></td>
	<td><%= @assignment.contribution_count_with_base('V', 'p') %></td>
      </tr>            
      <tr>
        <td><strong>English Contributions</strong></td>
	<td><%= @assignment.contribution_count('E') %></td>
      </tr>            
      <tr>
        <td><strong>Total Contributions</strong></td>
	<td><%= @assignment.total_contribution_count %></td>
      </tr>            
      <tr>
        <td><strong>Number of Sentences</strong></td>
	<td><%= assign_sen_count %></td>
      </tr>            
      <tr>
        <td><strong>Total Time (s)</strong></td>
	<td><%= assign_total_time %></td>
      </tr>            
      <tr>
        <td><strong>- Vote Time (s)</strong></td>
	<td><%= assign_vote_time %></td>
      </tr>            
      <tr>
        <td><strong>- Create Time (s)</strong></td>
	<td><%= assign_create_time %></td>
      </tr>            
      <tr>
        <td><strong>Time/Sentence (s)</strong></td>
        <td><%= format_time_per_sentence(@assignment.role, assign_total_time, assign_vote_contrib_count) %></td>
      </tr>            
      <tr>
        <td><strong>% Complete</strong></td>
        <td><%= format_percent_complete(@assignment.role, votes, sens) %></td>
      </tr>            
      <tr>
        <td><strong>Total Top Edits</strong></td>
        <td><%= m_top_edit_count + t_top_edit_count + z_top_edit_count %></td>
      </tr>            
      <tr>
        <td><strong>- Majority Top Edits</strong></td>
	<td><%= m_top_edit_count %></td>
      </tr>            
      <tr>
        <td><strong>- Tie Top Edits</strong></td>
	<td><%= t_top_edit_count %></td>
      </tr>            
      <tr>
        <td><strong>- Zero-vote Top Edits</strong></td>
	<td><%= z_top_edit_count %></td>
      </tr>            
      <tr>
        <td><strong>- Not Top Edits</strong></td>
	<td><%= n_top_edit_count %></td>
      </tr>            
      <tr>
        <td><strong>Total Modifications</strong></td>
        <td><%= @assignment.mods_count %></td>
      </tr>            

<% if current_user.cur_assign and (current_user.cur_assign.role == 'MT' or current_user.cur_assign.role == 'HT' or current_user.cur_assign.role == 'NT' or current_user.cur_assign.role == 'EP') %>
      <tr>
        <td><strong>Content Imported</strong></td>
        <td><%= @assignment.ci %></td>
      </tr>            
      <tr>
        <td><strong>Content</strong></td>
  <% if @assignment.ci %>
	<td><%= link_to 'Delete Content', { controller: 'assignments', action: 'destroy_contributions', params: {id: @assignment.id} }, data: { confirm: 'Are you sure you want to delete all contributions for this assignment?' }, class: 'btn btn-xs btn-danger' %></td>
  <% else %>
	<td><%= link_to 'Validate Content', validate_content_form_assignment_path, class: 'btn btn-xs btn-primary' %></td>
	<td><%= link_to 'Import Content', import_content_form_assignment_path, class: 'btn btn-xs btn-primary' %></td>
  <% end %>
      </tr>
<% end %>

<% if current_user.cur_assign and (current_user.cur_assign.role == 'LA' or current_user.cur_assign.role == 'TA' or current_user.cur_assign.role == 'EP') %>
      <tr>
        <td><strong>Text Content Exported</strong></td>
        <td><%#= @assignment.ce %></td>
      </tr>            
      <tr>
        <td><strong>Text Content</strong></td>
	<td><%= link_to 'Export Text Content', new_text_export_path, class: 'btn btn-xs btn-primary' %></td>
      </tr>
<% end %>

<%# if current_user.cur_assign.role == 'TA' %>
<% if current_user.cur_assign and (current_user.cur_assign.role == 'LA' or current_user.cur_assign.role == 'TA') %>
      <tr>
        <td><strong>Dash Content Exported</strong></td>
        <td><%#= @assignment.ce %></td>
      </tr>            
      <tr>
        <td><strong>Dash Content</strong></td>
	<td><%= link_to 'Export Dash Content', new_dash_export_path, class: 'btn btn-xs btn-primary' %></td>
      </tr>
<% end %>

      <tr>
        <td><strong>Translation</strong></td>
        <td><%= link_to @assignment.translation.translation_text, message_translation_path(@assignment.translation.message, @assignment.translation) if @assignment.translation %></td>
      </tr>            
      <tr>
        <td><strong>User</strong></td>
        <td><%= link_to @assignment.user.username, user_path(@assignment.user) if @assignment.user %></td>
      </tr>
      <tr>
        <td><strong>Status</strong></td>
        <td><%= @assignment.status %></td>
      </tr>
      <tr>
        <td><strong>Final Create contributions</strong></td>
        <td><%= @assignment.ccs %></td>
      </tr>
      <tr>
        <td><strong>- by klearing</strong></td>
        <td><%= @assignment.ccs_k %></td>
      </tr>
      <tr>
        <td><strong>- by modding</strong></td>
        <td><%= @assignment.ccs_m %></td>
      </tr>
      <tr>
        <td><strong>Final Vote contributions</strong></td>
        <td><%= @assignment.vcs %></td>
      </tr>
      <tr>
        <td><strong>- by accepting</strong></td>
        <td><%= @assignment.vcs_a %></td>
      </tr>
      <tr>
        <td><strong>- by creating</strong></td>
        <td><%= @assignment.vcs_c %></td>
      </tr>
      <tr>
        <td><strong>- by topping</strong></td>
        <td><%= @assignment.vcs_t %></td>
      </tr>
      <tr>
        <td><strong>- by picking</strong></td>
        <td><%= @assignment.vcs_p %></td>
      </tr>
      <tr>
        <td><strong>Final Create+Vote time (s)</strong></td>
        <td><%= @assignment.ct + @assignment.vt if(@assignment.ct and @assignment.vt) %></td>
      </tr>
      <tr>
        <td><strong>- Final Create time (s)</strong></td>
        <td><%= @assignment.ct %></td>
      </tr>
      <tr>
        <td><strong>- Final Vote time (s)</strong></td>
        <td><%= @assignment.vt %></td>
      </tr>
      <tr>
        <td><strong>Final Total Top Edits</strong></td>
        <td><%= @assignment.majtes + @assignment.tietes if(@assignment.majtes and @assignment.tietes) %></td>
      </tr>
      <tr>
        <td><strong>- Final Majority Top Edits</strong></td>
        <td><%= @assignment.majtes %></td>
      </tr>
      <tr>
        <td><strong>- Final Tie Top Edits</strong></td>
        <td><%= @assignment.tietes %></td>
      </tr>
      <tr>
        <td><strong>Final Percent Top Edits</strong></td>
        <td><%= '%.1f' % ((@assignment.majtes + @assignment.tietes)/@assignment.translation.senc.to_f*100) if(@assignment.majtes and @assignment.tietes) %></td>
      </tr>
      <tr>
        <td><strong>Notes</strong></td>
        <td><%= @assignment.notes %></td>
      </tr>
    </tbody>
  </table>

  <div class='show-actions'>
    <%= link_to 'Edit', edit_assignment_path(@assignment), class: 'btn btn-xs btn-primary' %>
    <%= link_to 'Delete', assignment_path(@assignment), method: :delete, data: { confirm: 'Are you sure you want to delete the assignment?'}, class: 'btn btn-xs btn-danger' %>
    <%= link_to 'View ALL Assignments', assignments_path, class: 'btn btn-xs btn-success' %>
    <%= link_to 'New Assignment', new_assignment_path(@assignment), class: 'btn btn-xs btn-primary' %>
    <br/><br/>
    &nbsp;
    <%= link_to 'New Contribution', new_contribution_path, class: 'btn btn-xs btn-primary' %>
    <%#= link_to 'Delete Translate Contributions', { controller: 'assignments', action: 'destroy_translate_contributions', params: {id: @assignment.id} }, data: { confirm: 'Are you sure you want to delete all translate contributions for this assignment?' }, class: 'btn btn-xs btn-danger' %>
  </div>

  <!--
  <div align='center'>
    <%#= will_paginate @assignment.contributions %>
  </div>
  -->

  <div>
    <h3 align='center'>Contributions (commented out)</h3>
  </div>
  <!-- causes timeout in prd for long messages - not that usefull anyway
  <div>
    <h3 align='center'>Contributions</h3>
    <table class='table table-striped table-condensed'>
      <thead>
	<tr>
          <td><strong>Id</strong></td>
          <td><strong>Kind</strong></td>
          <td><strong>Edit</strong></td>
        </tr>
      </thead>
      <tbody>
<% @assignment.contributions.each do |c| %>
	<tr>
          <td><%#= link_to c.id, contribution_path(c) %></td>
          <td><%#= c.kind %></td>
          <td><%#= link_to "#{c.edit.edit_text}", sentence_edit_path(c.edit.sentence, c.edit) if(c.edit.sentence) %></td> 
	  <td><%#= link_to 'Edit', edit_contribution_path(c) %></td>
	  <td><%#= link_to 'Delete', c, method: :delete, data: { confirm: 'Are you sure you want to delete this Contribution?' } %></td>
        </tr> 
<% end %>
      </tbody>
    </table>
  </div>  
  -->

  <!--
  <div align='center'>
    <%#= will_paginate @assignment.contributions %>
  </div>
  -->

</div>