config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions" }
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  resources :users

  get '/enable_auto_advance_after_vote', to: 'edits#enable_auto_advance_after_vote'
  get '/disable_auto_advance_after_vote', to: 'edits#disable_auto_advance_after_vote'
  get '/enable_auto_advance_after_save', to: 'edits#enable_auto_advance_after_save'
  get '/disable_auto_advance_after_save', to: 'edits#disable_auto_advance_after_save'

  root 'pages#home'

  get '/help', to: 'pages#help'
  get '/about', to: 'pages#about'
  get '/timeout', to: 'pages#timeout'

  resources :messages do
    resources :translations
  end
  get '/all_translations', to: 'translations#all_translations'

  resources :translations do
    resources :sentences
    member do
      get :import_lookup_form
      post :import_lookup
      get :randomize_translate_contributions
    end
  end
  get '/destroy_sentences', to: 'translations#destroy_sentences'
  get '/destroy_lookups', to: 'translations#destroy_lookups'

  resources :lookups

  resources :sentences do
    resources :edits do
      member do
        post :vote
      end
    end
    member do
      get :next
      get :prev
      get :increase_context
      get :decrease_context
      get :timeout
      get :multi_button_action
      get :show_search
      get :show_preview
    end
  end

  
  resources :assignments do
    member do
      get :import_content_form
      post :import_content
      get :validate_content_form
      post :validate_content
      get :report
    end
  end
  get '/destroy_contributions', to: 'assignments#destroy_contributions'
  get '/status_assignments', to: 'assignments#status_assignments'
  get '/status_assignments_seven_day', to: 'assignments#status_assignments_seven_day'
  get '/status_assignments_all_time_work', to: 'assignments#status_assignments_all_time_work'
  get '/status_assignments_all_time_translations', to: 'assignments#status_assignments_all_time_translations'
  get '/team_assignments', to: 'assignments#team_assignments'

  resources :contributions

  post '/sentences/:sentence_id/edits/:id/save_modified_clone', :to => 'edits#save_modified_clone'

  get '/users/:id/assignments/:id/switch', to: 'users#switch_current_assignment'

  resources :text_exports, :only => [:new, :create]

  resources :dash_exports, :only => [:new, :create]

end

app/models/translation.rb
#class Translation < ActiveRecord::Base
class Translation < ApplicationRecord
  has_many :assignments
  has_many :users, through: :assignments

  belongs_to :message

  has_many :sentences
  has_many :lookups

  belongs_to :eng_tran, class_name: "Translation", foreign_key: "eng_tran_id"

  validates :lan, presence: true, length: { minimum: 3, maximum: 4 }
  validates :tran_title, presence: true, length: { minimum: 3, maximum: 70 }
  validates :descrip, presence: false, length: { minimum: 0, maximum: 500 }
  validates :blkc, numericality: { only_integer: true }
  validates :subc, numericality: { only_integer: true }
  validates :senc, numericality: { only_integer: true }
  validates :xcrip, presence: true
  validates :message_id, presence: true

  attr_accessor :file_name

=begin
  def translator

  end

  def translator=(userid)
    Assignment.new(user_id: userid)
  end

  def translator_kind

  end

  def translator_kind=(kind)
    if(kind == 'MT
  end
=end

  def translation_text
    "[#{lan} #{blkc}.#{subc}.#{senc}.#{xcrip}] #{message.dod}#{message.tod} #{message.title} (#{version})"
  end
  
  def status_text
    "#{message.dod}#{message.tod} #{message.title}"
  end
  
  def eng_tran_text
    if eng_tran
      "[#{eng_tran.lan} #{eng_tran.blkc}.#{eng_tran.subc}.#{eng_tran.senc}.#{eng_tran.xcrip}]"
    else
      "N/A"
    end
  end
end

app/controllers/translations_controller.rb
class TranslationsController < ApplicationController
  before_action :get_message, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  before_action :set_translation, only: [:show, :edit, :update, :destroy]
  before_action :require_admin

  def all_translations
    @all_translations = Translation.all
  end

  # GET /translations
  # GET /translations.json
  def index
    # @translations = Translation.all
    # @translations = Translation.paginate(page: params[:page], per_page: 3)
    @translations = @message.translations
  end

  # GET /translations/1
  # GET /translations/1.json
  def show
  end

  # GET /translations/new
  def new
    #@message_options = Message.all.map { |m| [m.descriptor + " " + m.title, m.id] }
    #@translator_options = User.all.map { |u| [u.username, u.id] }
	  
    @translation = Translation.new
  end

  # GET /translations/1/edit
  def edit
    #@message_options = Message.all.map { |m| [m.descriptor + " " + m.title, m.id] }
  end

  # POST /translations
  # POST /translations.json
  def create
    # determine if message has been imported already
    language = params[:translation][:lan]
    transcription = params[:translation][:xcrip]
    #translator = params[:translation][:file_name]
    #translator = @message.translations.
    #translationsOTH = @message.translations.where(lan: language, xcrip: transcription, )
#Translation.joins(:users).where(assignments: {role: 'TRANSLATOR'}, users: {username: 'steest'}, translations: {message_id: @message.id})
    #populate translators drop-down
    #@translators = User.joins(:roles).where(roles: {name: 'TRANSLATOR'}) 
	  
    
    ###@translation = Translation.new(translation_params)
    @translation = @message.translations.new(translation_params)


    if @translation.save
      flash[:success] = "Translation was successfully created"
      redirect_to message_translation_path(@message, @translation)
    else
      render 'new'
    end
  end

  # PATCH/PUT /translations/1
  # PATCH/PUT /translations/1.json
  def update
    if @translation.update(translation_params)
      flash[:success] = "Translation was successfully updated"
      redirect_to message_translation_path(@message, @translation)
    else
      render 'edit'
    end
  end

  # DELETE /translations/1
  # DELETE /translations/1.json
  def destroy
    @translation.destroy  
    flash[:danger] = "Translation was successfully deleted"
    redirect_to message_translations_path
  end

  def destroy_sentences
    #get_message
    #set_translation
    @translation = Translation.find(params[:id])
    @translation.sentences.each do |sentence|
      sentence.destroy
    end
    flash[:danger] = 'All sentences for this translation deleted'
    redirect_to message_translation_path(@translation.message, @translation)
  end

  def destroy_lookups
    @translation = Translation.find(params[:id])

    # determine the lookups to be deleted
    lookups = @translation.lookups

    num_of_lookups = lookups.length
    puts "num_of_lookups: #{num_of_lookups}"
    if num_of_lookups > 0
      lookups.each do |lu|
        lu.destroy
      end
    
      #mark as not imported 
      @translation.update(li: false) 

      flash[:danger] = "#{num_of_lookups} lookups for this translation deleted"
    else
      flash[:danger] = 'No lookups for this translation deleted'
    end

    redirect_to message_translation_path(@translation.message, @translation)
  end

  def import_lookup_form
    @translation = Translation.find(params[:id])
  end

  def import_lookup
    @translation = Translation.find(params[:id])

    # upload file
    uploaded_io = params[:translation][:file_name]
    File.open(Rails.root.join('public', uploaded_io.original_filename), 'wb') do |file|
      file.write(uploaded_io.read)
    end

    # read uploaded file and populate database
    num_of_lookups = 0 
    File.foreach("#{Rails.root}/public/#{uploaded_io.original_filename}").with_index do |line, line_num|
      #next if line_num == 0

      if !line.strip.empty?
        puts line

	# get line parts
        line_parts = line.split(' ', 3) #split by space into 3 parts

	# get blk
        blk = line_parts[0]

	# get sub
        sub = line_parts[1]

	# get rsub
        rsub = line_parts[2]

        # create lookup
        new_lookup = Lookup.create(blk: blk, sub: sub, rsub: rsub, translation: @translation)
	if new_lookup
          puts "new_lookup: #{new_lookup.blk} #{new_lookup.sub} #{new_lookup.rsub}" 
        else
          flash[:danger] = "ERROR: Could not create lookup #{new_lookup.blk} #{new_lookup.sub} #{new_lookup.rsub}"
          redirect_to message_translation_path(@translation.message, @translation)
        end

        new_lookup = nil
        num_of_lookups += 1
      end #if
    end #File

    #delete uploaded file
    #todo
    
    #mark as imported 
    @translation.update(li: true) 
    
    flash[:success] = "#{num_of_lookups} lookups for this translation imported"
    redirect_to message_translation_path(@translation.message, @translation)
  end

  def randomize_translate_contributions
#number_of_translate_assignments = 2 
    number_of_translate_assignments = params[:number_of_translate_assignments].to_i
    puts "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ number_of_translate_assignments = #{number_of_translate_assignments}" 
    @translation = Translation.find(params[:id])
    num_of_randomizations = 0 
    @translation.sentences.each do |sentence|
      edits = sentence.edits.order('created_at')
      if edits.length == number_of_translate_assignments #there are ONLY translate (T) contributions when this is done, i.e. no Vote or Create contributions yet
        times = []
        edits.each { |e| times << e.created_at } #populate times array with the created_at of each edit
        random_times = times.sample(edits.length) #take random sample of the created_at times of all edits because edits are ordered by created_at on proofread page
        edits.each_with_index do |edit, i|
          edit.created_at = random_times[i]
	  edit.save
        end
	puts "++++++++++++++++++++++++++++++++++++++++++++++++ Randomization performed for sentence with rsen=#{sentence.rsen}"
        num_of_randomizations += 1 
      elsif edits.length > number_of_translate_assignments
        puts "------------------------------------------------ Number of edits for sentence with rsen=#{sentence.rsen} is #{edits.length}. That is greater than the number of translate assignments (#{number_of_translate_assignments}). Some Create (C) edits may have already been added, or the number of translate assignments are wrong  - no randomization performed."
      else #edits.length < number_of_translate_assignments
        puts "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Number of edits for sentence with rsen=#{sentence.rsen} is #{edits.length}. That is less than the number of translate assignments (#{number_of_translate_assignments}). This is not allowed  - no randomization performed."
      end
    end

    #mark as randomized 
    @translation.update(li: true) 
    
    flash[:success] = "#{num_of_randomizations} out of #{@translation.sentences.length} randomizations have been performed for this translation. For each sentence, the number of edits must equal the number of translate assignments exactly, else a randomization will not be performed for that sentence."
    redirect_to message_translation_path(@translation.message, @translation)
  end

  private
    def get_message
      @message = Message.find(params[:message_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_translation
      # @translation = Translation.find(params[:id])
      @translation = @message.translations.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def translation_params
      params.require(:translation).permit(:lan, :tran_title, :eng_tran_id, :descrip, :blkc, :subc, :senc, :xcrip, :message_id, :file_name, :li, :number_of_translate_assignments, :pubdate, :version)
    end

    def require_admin
      if !user_signed_in? || (user_signed_in? and !current_user.admin?)
        flash[:danger] = 'Only admins can perform that action'
        redirect_to root_path
      end
    end
    
end

app/helpers/translations_helper.rb
module TranslationsHelper
  def lookup_link(message)
    if @translation.li
      link_to 'Delete Lookup', { controller: 'translations', action: 'destroy_lookups', params: {id: @translation.id} }, data: { confirm: 'Are you sure you want to delete all lookups for this translation?' }, class: 'btn btn-xs btn-danger'
    else
      link_to 'Import Lookup', import_lookup_form_translation_path, message_id: message.id, class: 'btn btn-xs btn-primary'
    end 
  end
end

app/views/translations/all_translations.html.erb
<div class='container'>
  <h1 align='center'>All Translations</h1>
  <div align='center'>
    <%#= will_paginate @translations %>
  </div>
  <table class='table table-bordered table-hover'>
    <thead>
      <tr>
        <th>Id</th>
        <th>Language</th>
        <th>Translated Title</th>
        <th>ENG Translation</th>
        <th>Description</th>
        <th>Block Count</th>
        <th>Sub-block Count</th>
        <th>Sentence Count</th>
        <th>Transcription</th>
        <th>Lookup Imported</th>
        <th>Message</th>
        <th colspan="2">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @all_translations.each do |translation| %>
        <tr>
          <td><%= link_to translation.id, message_translation_path(translation.message, translation) %></td>
          <td><%= translation.lan %></td>
          <td><%= translation.tran_title %></td>
          <td><%= translation.eng_tran_text %></td>
          <td><%= truncate(translation.descrip, length: 10) %></td>
          <td><%= translation.blkc %></td>
          <td><%= translation.subc %></td>
          <td><%= translation.senc %></td>
          <td><%= translation.xcrip %></td>
          <td><%= translation.li %></td>
          <td><%= link_to translation.message.message_text, message_path(translation.message) %></td>
          <td><%= link_to 'Edit', edit_message_translation_path(translation.message, translation) %></td>
	  <td><%= link_to 'Destroy', [translation.message, translation], method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div align='center'>
    <%#= will_paginate @translations %>
  </div>  
</div>

app/views/translations/edit.html.erb
<h1 align='center'>Editing Translation</h1>

<%= render 'form' %>

app/views/translations/import_lookup_form.html.erb
<%#= render 'shared/errors', obj: @assignment %>

<div class='row'>
  <div class='col-xs-12'>
	  <%= form_tag({controller: "translations", action: "import_lookup"}, multipart: true, :html => {class: 'form-horizontal', role: 'form'}) do %>

      <div class='form-group'>
        <div class='control-label col-sm-2'>
          <%= label_tag(:q, 'File Name') %>
        </div>
        <div class='col-sm-8'>
          <%= file_field_tag "translation[file_name]", class: 'btn btn-primary' %>
          <!--<input type="file" id="myFile">-->
          <!-- to style: google search -- file input rails  -->
          <!--http://stackoverflow.com/questions/33028255/rails-4-how-to-apply-custom-css-to-rails-form-file-field
          http://stackoverflow.com/questions/14509449/styling-file-upload-button-for-simple-form-for-with-bootstrap-in-rails-3 -->
        </div>
      </div>

      <div class="form-group">
        <div class='col-sm-offset-2 col-xs-10'>
		<%= submit_tag('Import Lookup', class: 'btn btn-primary btn-lg') %>
		<%#= submit_tag('Import Lookup', id: "#{@translation.id}", class: 'btn btn-primary btn-lg') %>
        </div>
      </div>      
    <% end %>

    <div class='col-xs-4 col-xs-offset-4'>
      [ <%= link_to "Cancel request and return to assignment", translation_path %> ]
    </div>    

  </div>
</div>

app/views/translations/index.html.erb
<div class='container'>
  <h1 align='center'>Translations</h1>
  <div align='center'>
    <%#= will_paginate @translations %>
  </div>
  <table class='table table-condensed table-bordered table-hover'>
    <thead>
      <tr>
        <th>Language</th>
        <th>Translated Title</th>
        <th>ENG Translation</th>
        <th>Description</th>
        <th>Block Count</th>
        <th>Sub-block Count</th>
        <th>Sentence Count</th>
        <th>Transcription</th>
        <th>Message</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @translations.each do |translation| %>
        <tr>
          <td><%= translation.lan %></td>
          <td><%= translation.tran_title %></td>
          <td><%= translation.eng_tran_text %></td>
          <td><%= truncate(translation.descrip, length: 10) %></td>
          <td><%= translation.blkc %></td>
          <td><%= translation.subc %></td>
          <td><%= translation.senc %></td>
          <td><%= translation.xcrip %></td>
          <td><%= translation.message %></td>
          <td><%= link_to 'Show', [@message, translation] %></td>
          <td><%= link_to 'Edit', edit_message_translation_path(@message, translation) %></td>
          <td><%= link_to 'Destroy', [@message, translation], method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div align='center'>
    <%#= will_paginate @translations %>
  </div>  
</div>

app/views/translations/new.html.erb
<h1 align='center'>New Translation</h1>

<%= render 'form' %>

app/views/translations/show.html.erb
<h2 align='center'>Translation</h2>

<div class='col-xs-8 col-xs-offset-2'>

  <table class='table table-striped'>
    <tbody>
      <tr>
        <td><strong>Id</strong></td>
        <td><%= @translation.id %></td>
      </tr>
      <tr>
        <td><strong>Language</strong></td>
        <td><%= @translation.lan %></td>
      </tr>
      <tr>
        <td><strong>Translated Title</strong></td>
        <td><%= @translation.tran_title %></td>
      </tr>
      <tr>
        <td><strong>ENG Translation</strong></td>
        <td><%= @translation.eng_tran_text %></td>
      </tr>
      <tr>
        <td><strong>Description</strong></td>
        <td><%= simple_format(@translation.descrip) %></td>
      </tr>            
      <tr>
        <td><strong>Block Count</strong></td>
        <td><%= @translation.blkc %></td>
      </tr>
      <tr>
        <td><strong>Sub-block Count</strong></td>
        <td><%= @translation.subc %></td>
      </tr>
      <tr>
        <td><strong>Sentence Count</strong></td>
        <td><%= @translation.senc %></td>
      </tr>
      <tr>
        <td><strong>Transcription</strong></td>
        <td><%= @translation.xcrip %></td>
      </tr>
<% if @translation.lan == 'ENG' %>
      <tr>
        <td><strong>Lookup Imported</strong></td>
        <td><%= @translation.li %></td>
      </tr>
      <tr>
        <td><strong>Lookup</strong></td>
        <td><%= lookup_link(@message) %></td>
      </tr>
<% else %>
      <tr>
        <td><strong>Translate Contributions Randomized</strong></td>
        <td><%= @translation.li %></td>
      </tr>
      <tr>
  <% if !@translation.li %>
        <td><strong>Randomization</strong></td>
	<td>
          <%= form_tag({controller: "translations", action: "randomize_translate_contributions"}, method: 'get', multipart: true, :html => {class: 'form-horizontal', role: 'form'}) do %>
            <div class='form-group'>
              <div class='control-label col-sm-2'>
                <%= label_tag(:number_of_translate_assignments, 'Number of translate assignments') %>
              </div>
              <div class='col-sm-8'>
                <%= text_field_tag :number_of_translate_assignments %>
              </div>
            </div>
            <div class="form-group">
              <div class='col-sm-offset-2 col-xs-10'>
	        <%= submit_tag('Randomize Translate Contributions', data: {confirm: 'Are you sure you want to randomize the translate contributions for this translation?'}, class: 'btn btn-primary btn-xs') %>
              </div>
            </div>      
          <% end %>
        </td>
  <% end %>
      </tr>
<% end %>
      <tr>
        <td><strong>Message</strong></td>
	<td><%= link_to "#{@translation.message.message_text}", message_path(@translation.message) %></td>
      </tr>
      <tr>
        <td><strong>Publication Date</strong></td>
        <td><%= @translation.pubdate %></td>
      </tr>
      <tr>
        <td><strong>Version</strong></td>
        <td><%= @translation.version %></td>
      </tr>
    </tbody>
  </table>

  <div class='show-actions'>
    <%= link_to 'Edit', edit_message_translation_path(@message, @translation), class: 'btn btn-xs btn-primary' %>
    <%= link_to 'Delete', message_translation_path(@message, @translation), method: :delete, data: { confirm: 'Are you sure you want to delete the translation?'}, class: 'btn btn-xs btn-danger' %>
    <%= link_to 'View Translations', message_translations_path, class: 'btn btn-xs btn-success' %>
    <%= link_to 'New Translation', new_message_translation_path(@message, @translation), class: 'btn btn-xs btn-primary' %>
    <br/><br/>
    <%= link_to 'New Assignment', new_assignment_path, class: 'btn btn-xs btn-primary' %>
    <%= link_to 'New Sentence', new_translation_sentence_path(@translation), class: 'btn btn-xs btn-primary' %>
    <%= link_to 'Delete Sentences', { controller: 'translations', action: 'destroy_sentences', params: {message_id: @translation.message.id, id: @translation.id} }, data: { confirm: 'Are you sure you want to delete all sentences for this translation?' }, class: 'btn btn-xs btn-danger' %>
  </div>

  <div>
    <h3 align='center'>Assignments</h3>
    <table class='table table-striped table-condensed'>
      <thead>
	<tr>
          <td><strong>Id</strong></td>
          <td><strong>Role</strong></td>
          <td><strong>Active</strong></td>
          <td><strong>Status</strong></td>
          <td><strong>CI</strong></td>
          <td><strong>Place</strong></td>
          <td><strong>TCs</strong></td>
          <td><strong>CCs</strong></td>
          <td><strong>VCs</strong></td>
          <td><strong>ECs</strong></td>
          <td><strong>TotCs</strong></td>
          <td><strong>#Sens</strong></td>
          <td><strong>VT</strong></td>
          <td><strong>CT</strong></td>
          <td><strong>TotT</strong></td>
          <td><strong>M TEs</strong></td>
          <td><strong>T TEs</strong></td>
          <td><strong>Z TEs</strong></td>
          <td><strong>N TEs</strong></td>
          <td><strong>TotTEs</strong></td>
          <td><strong>User</strong></td>
        </tr>
      </thead>
      <tbody>
<% @translation.assignments.each do |a| %>
	<tr>
  <% #do here, else will be calculated multiple times %>
  <% assign_vote_time = a.vote_time %>
  <% assign_create_time = a.create_time %>
  <% assign_total_time = assign_vote_time + assign_create_time %>
  <% assign_sen_count = a.sentence_count if a.translation %>
          <td><%= link_to a.id, assignment_path(a) %></td>
          <td><%= a.role %></td>
          <td><%= a.active %></td>
          <td><%= a.status %></td>
          <td><%= a.ci %></td>
          <td><%= a.place %></td>
          <td><%= a.contribution_count('T') %></td>
          <td><%= a.contribution_count('C') %></td>
          <td><%= a.contribution_count('V') %></td>
          <td><%= a.contribution_count('E') %></td>
          <td><%= a.total_contribution_count %></td>
	  <td><%= assign_sen_count %></td>
	  <td><%= assign_vote_time %></td>
	  <td><%= assign_create_time %></td>
	  <td><%= assign_total_time %></td>
  <% m_top_edit_count = a.top_edit_count('M') %>
  <% t_top_edit_count = a.top_edit_count('T') %>
  <% z_top_edit_count = a.top_edit_count('Z') %>
  <% n_top_edit_count = a.top_edit_count('N') %>
          <td><%= m_top_edit_count %></td>
          <td><%= t_top_edit_count %></td>
          <td><%= z_top_edit_count %></td>
          <td><%= n_top_edit_count %></td>
          <td><%= m_top_edit_count + t_top_edit_count + z_top_edit_count %></td>
	  <td><%= link_to a.user.username, user_path(a.user) if a.user %></td>
	  <td><%= link_to 'Edit', edit_assignment_path(a) %></td>
	  <td><%= link_to 'Delete', a, method: :delete, data: { confirm: 'Are you sure you want to delete this Assignment?' } %></td>
        </tr> 
<% end %>
      </tbody>
    </table>
  </div>  

  <div>
    <h3 align='center'>Sentences</h3>
    <table class='table table-striped table-condensed'>
      <thead>
	<tr>
          <td><strong>Id</strong></td>
          <td><strong>Blk</strong></td>
          <td><strong>Sub</strong></td>
          <td><strong>RSub</strong></td>
          <td><strong>Sen</strong></td>
          <td><strong>RSen</strong></td>
          <td><strong>Typ</strong></td>
          <td><strong>Tie</strong></td>
        </tr>
      </thead>
      <tbody>
<% @translation.sentences.order(:rsen).each do |s| %>
	<tr>
          <td><%= link_to s.id, translation_sentence_path(@translation, s) %></td>
          <td><%= s.blk %></td>
          <td><%= s.sub %></td>
          <td><%= s.rsub %></td>
          <td><%= s.sen %></td>
          <td><%= s.rsen %></td>
          <td><%= s.typ %></td>
          <td><%= s.tie %></td>
	  <td><%= link_to 'Edit', edit_translation_sentence_path(@translation, s) %></td>
	  <td><%= link_to 'Delete', s, method: :delete, params: {translation_id: @translation.id, id: s.id}, data: { confirm: 'Are you sure you want to delete this Sentence?' } %></td>
        </tr> 
<% end %>
      </tbody>
    </table>
  </div>  

  <div>
    <h3 align='center'>Lookups</h3>
    <table class='table table-striped table-condensed'>
      <thead>
	<tr>
          <td><strong>Id</strong></td>
          <td><strong>Blk</strong></td>
          <td><strong>Sub</strong></td>
          <td><strong>RSub</strong></td>
        </tr>
      </thead>
      <tbody>
<% @translation.lookups.each do |l| %>
	<tr>
          <td><%= l.id %></td>
          <td><%= l.blk %></td>
          <td><%= l.sub %></td>
          <td><%= l.rsub %></td>
	  <td><%#= link_to 'Edit', edit_translation_sentence_path(@translation, s) %></td>
	  <td><%#= link_to 'Delete', s, method: :delete, params: {translation_id: @translation.id, id: s.id}, data: { confirm: 'Are you sure you want to delete this Sentence?' } %></td>
        </tr> 
<% end %>
      </tbody>
    </table>
  </div>  

</div>