config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions" }
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  resources :users

  get '/enable_auto_advance_after_vote', to: 'edits#enable_auto_advance_after_vote'
  get '/disable_auto_advance_after_vote', to: 'edits#disable_auto_advance_after_vote'
  get '/enable_auto_advance_after_save', to: 'edits#enable_auto_advance_after_save'
  get '/disable_auto_advance_after_save', to: 'edits#disable_auto_advance_after_save'

  root 'pages#home'

  get '/help', to: 'pages#help'
  get '/about', to: 'pages#about'
  get '/timeout', to: 'pages#timeout'

  resources :messages do
    resources :translations
  end
  get '/all_translations', to: 'translations#all_translations'

  resources :translations do
    resources :sentences
    member do
      get :import_lookup_form
      post :import_lookup
      get :randomize_translate_contributions
    end
  end
  get '/destroy_sentences', to: 'translations#destroy_sentences'
  get '/destroy_lookups', to: 'translations#destroy_lookups'

  resources :lookups

  resources :sentences do
    resources :edits do
      member do
        post :vote
      end
    end
    member do
      get :next
      get :prev
      get :increase_context
      get :decrease_context
      get :timeout
      get :multi_button_action
      get :show_search
      get :show_preview
    end
  end

  
  resources :assignments do
    member do
      get :import_content_form
      post :import_content
      get :validate_content_form
      post :validate_content
      get :report
    end
  end
  get '/destroy_contributions', to: 'assignments#destroy_contributions'
  get '/status_assignments', to: 'assignments#status_assignments'
  get '/status_assignments_seven_day', to: 'assignments#status_assignments_seven_day'
  get '/status_assignments_all_time_work', to: 'assignments#status_assignments_all_time_work'
  get '/status_assignments_all_time_translations', to: 'assignments#status_assignments_all_time_translations'
  get '/team_assignments', to: 'assignments#team_assignments'

  resources :contributions

  post '/sentences/:sentence_id/edits/:id/save_modified_clone', :to => 'edits#save_modified_clone'

  get '/users/:id/assignments/:id/switch', to: 'users#switch_current_assignment'

  resources :text_exports, :only => [:new, :create]

  resources :dash_exports, :only => [:new, :create]

end

app/models/sentence.rb
#class Sentence < ActiveRecord::Base
class Sentence < ApplicationRecord
  belongs_to :translation
  has_many :edits
  validates :blk, numericality: { only_integer: true }
  validates :rsub, numericality: { only_integer: true }
  validates :sen, numericality: { only_integer: true }
  validates :typ, presence: true, length: { minimum: 1, maximum: 1 }
  validates :translation_id, presence: true

  attr_accessor :search_term #virtual attribute: not persisted

  def sentence_text
    "#{blk}.#{sub}.#{rsub}.#{sen}.#{rsen}.#{typ}"
  end

  #searchable do
  #  text :typ
  #  #text :edits do
  #  #  edits.map { |edit| edit.content } 
  #  #end
  #end
end

app/controllers/sentences_controller.rb
class SentencesController < ApplicationController
  before_action :get_translation, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  before_action :set_sentence, only: [:show, :edit, :update, :destroy]
  before_action :require_admin, only: [:index]
  before_action :require_sign_in

  ###helper_method :voted_for, :created, :top_edit_class
  ###helper_method :voted_for, :created
  helper_method :sentence_vote_contribution
  helper_method :sentence_vote_time
  helper_method :sentence_create_contributions
  helper_method :sentence_create_time
  #helper_method :vote_timer_status
  #helper_method :create_timer_status

  # GET /sentences
  # GET /sentences.json
  def index
    #@sentences = Sentence.all
    #@sentences = @translation.sentences
    @sentences = @translation.sentences.paginate(page: params[:page], per_page: 10)
  end

  def multi_button_action 
    #require_cur_assign
    if !current_user.cur_assign
      #flash[:danger] = 'You do not have an assignment currently'
      redirect_to root_path and return
    end
    @translation = Translation.find(params[:translation_id])
    if params["go_button"] # '>>'
      #puts "go_button was clicked ......................."
      go()
    elsif params["search_button"] # 'spyglass'
      #puts "search_button was clicked ......................."
      search()
    elsif params["place_button"] # '|^|' (bookmark)
      #puts "place_button was clicked ......................."
      place()
    elsif params["preview_button"] # 'eye'
      #puts "preview_button was clicked ......................."
      preview()
    else
      puts "ERROR: no option!!!!!!!"
    end
  end

  def go 
    # validate params (unless a param can be parsed to an integer, a nil is returned)
    # can't use standard way as for persisted models
    blk = Integer(params[:blk]) rescue nil
    rsub = Integer(params[:rsub]) rescue nil
    rsen = Integer(params[:rsen]) rescue nil

    # find destination sentence
    if blk #go to blk
      if not blk.between?(1, @translation.blkc)
        #flash[:danger] = "You attempted to go to block #{blk}. Blocks vary from 1 to #{@translation.blkc}."
        flash[:danger] = "You attempted to go to block #{blk}. This number is out of range."
        redirect_back(fallback_location: root_path) and return
      else
        sentence = @translation.sentences.where(blk: blk, sub: 1, sen: 1).first
      end
    elsif rsub #go to rsub
      if not rsub.between?(1, @translation.subc)
        #flash[:danger] = "You attempted to go to running subblock #{rsub}. Subblocks vary from 1 to #{@translation.subc}."
        flash[:danger] = "You attempted to go to running subblock #{rsub}. This number is out of range."
        redirect_back(fallback_location: root_path) and return
      else
        sentence = @translation.sentences.where(rsub: rsub, sen: 1).first
      end
    elsif rsen #go to rsen
      if not rsen.between?(1, @translation.senc)
        #flash[:danger] = "You attempted to go to running sentence #{rsen}. Running sentences vary from 1 to #{@translation.senc}."
        flash[:danger] = "You attempted to go to running sentence #{rsen}. This number is out of range."
        redirect_back(fallback_location: root_path) and return
      else
        sentence = @translation.sentences.where(rsen: rsen).first
      end
    else #no usable input
      if current_user.admin?
        flash[:danger] = "Input is invalid. You provided Blk=#{params[:blk]}, RSub=#{params[:rsub]}, RSen=#{params[:rsen]}. Please supply a valid number in one of the input fields."
      else
        flash[:danger] = "Input is invalid. Please supply a valid sentence number to jump to."
      end
      redirect_back(fallback_location: root_path) and return
    end

    # update user's place
    if sentence
      current_user.cur_assign.update(place: sentence.rsen)
    else
      flash[:danger] = 'No target sentence found.'
    end

    # update vote time
    #vote_contrib = vote_contribution(sentence)
    #vote_contrib.update(effort_in_seconds: vote_contrib.effort_in_seconds + stop_vote_timer) if vote_contrib

    redirect_to translation_sentence_path(@translation, sentence)
  end

  def search
    session[:search_term] = params[:search_term]
    redirect_to show_search_sentence_path()
  end

  def show_search 
    require_cur_assign
    @sentence = Sentence.find(params[:id])
    @translation = @sentence.translation

    if session["search_term"].blank? #no usable input
      flash[:danger] = "Input is blank. Please supply a valid search term."
      redirect_back(fallback_location: root_path) and return
    else 
      term = session[:search_term].downcase

      #escape any single quotes for sql queries, i.e. all ' becomes ''
      term = term.gsub("'", "''")

      #ENG query
      sql_eng = "select s.rsen, e.content 
from edits as e
join sentences as s on e.sentence_id=s.id
join translations as t on s.translation_id=t.id
where t.id=#{@translation.eng_tran.id} and lower(e.content) LIKE '%#{term}%' order by s.rsen;"
      search_hits = ActiveRecord::Base.connection.execute(sql_eng)
      @hits_eng = search_hits.values
      
      #OTH query for edits owned by user
      sql_oth_own = "select distinct s.rsen, e.content 
from edits as e
join contributions as c on c.edit_id=e.id
join assignments as a on c.assignment_id=a.id
join users as u on a.user_id=u.id
join sentences as s on e.sentence_id=s.id
join translations as t on s.translation_id=t.id
where t.id=#{@translation.id} and u.id=#{current_user.id} and lower(e.content) LIKE '%#{term}%' order by s.rsen;"
      search_hits = ActiveRecord::Base.connection.execute(sql_oth_own)
      @hits_oth_own = search_hits.values

      #OTH query for edits NOT owned by user
      sql_oth_not = "select distinct s.rsen, e.content 
from edits as e
join contributions as c on c.edit_id=e.id
join assignments as a on c.assignment_id=a.id
join users as u on a.user_id=u.id
join sentences as s on e.sentence_id=s.id
join translations as t on s.translation_id=t.id
where t.id=#{@translation.id} and not u.id=#{current_user.id} and lower(e.content) LIKE '%#{term}%' order by s.rsen;"
      search_hits = ActiveRecord::Base.connection.execute(sql_oth_not)
      @hits_oth_not = search_hits.values
    end 
  end

  def place
    rsen = current_user.cur_assign.place
    sentence = @translation.sentences.where(rsen: rsen).first
    redirect_to translation_sentence_path(@translation, sentence)
  end

  def preview
    puts @sentence
    redirect_to show_preview_sentence_path()
  end

  def show_preview
    require_cur_assign
    @sentence = Sentence.find(params[:id])
    @translation = @sentence.translation

    #ensure session has a preview value - gone if cur_assign has been set to nil for de-activation
    if not session[:preview]
      session[:preview] = 20
    end
    lo = @sentence.rsen - session[:preview]
    hi = @sentence.rsen

    sql_eng = "select s.rsub, s.sen, s.typ, s.rsen, e.content 
from edits as e
join sentences as s on e.sentence_id=s.id
join translations as t on s.translation_id=t.id
where t.id=#{@translation.eng_tran.id} and (s.rsen between #{lo} and #{hi}) order by s.rsen;"
    preview_E_edits = ActiveRecord::Base.connection.execute(sql_eng)
    @preview_E = format_preview(preview_E_edits)

    sql_oth = "select s.rsub, s.sen, s.typ, s.rsen, e.content 
from edits as e
join sentences as s on e.sentence_id=s.id
join translations as t on s.translation_id=t.id
where t.id=#{@translation.id} 
and (s.rsen between #{lo} and #{hi}) 
and not e.top='N' 
order by s.rsen;"
    preview_O_edits = ActiveRecord::Base.connection.execute(sql_oth)
    @preview_O = format_preview(preview_O_edits)
  end

  def format_preview(preview_edits)
    preview = ''
    preview_edits.each do |e|
      if(['h', 'i', 'j'].include? e['typ'])
        preview << '<br/><br/>'
      elsif e['sen']==1
        preview << '<br/><br/>'
      elsif e['typ']=='s'
        preview << '<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
      elsif e['typ']=='p'
        preview << '<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
      elsif e['typ']=='q'
        preview << '<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
      elsif e['typ']=='c'
        preview << '<br/><br/>'
      end
      #preview << "[#{e['rsub']}.#{e['sen']}.#{e['typ']}] #{e['content']} " #to troubleshoot
      ##preview << eval("link_to(#{e['rsen']}, [@translation, @sentence])")
      ##preview << eval("<%= link_to(#{e['rsen']}, [@translation, @sentence]) %> ")
      preview << "#{e['rsen']}: #{e['content']} "
      #preview << "#{e['content']} " #maybe a config can add/remove rsen values?
    end
    return preview
  end

  def prev
    if !current_user.cur_assign
      #flash[:danger] = 'You do not have an assignment currently'
      redirect_to root_path and return
    end

    @translation = Translation.find(params[:translation_id])
    @sentence = Sentence.find(params[:id])

    # update vote time
    #vote_contrib = vote_contribution(@sentence)
    #vote_contrib.update(effort_in_seconds: vote_contrib.effort_in_seconds + stop_vote_timer) if vote_contrib

    #update rsen
    prev_rsen = @sentence.rsen - 1
    if prev_rsen < 1
      prev_rsen = 1
      flash[:danger] = 'This is the first sentence.'
    end
    current_user.cur_assign.update(place: prev_rsen)

    #update @pred_sentences
    #@pred_sentences= @translation.sentences.where(rsen: prev_rsen-5..prev_rsen-1)

    #update @sentence 
    @sentence = @translation.sentences.where(rsen: prev_rsen).first

    #update @succ_sentences
    #@succ_sentences= @translation.sentences.where(rsen: prev_rsen+1..prev_rsen+5)

    redirect_to translation_sentence_path(@translation, @sentence)
  end

  def next
    #require_cur_assign
    if !current_user.cur_assign
      #flash[:danger] = 'You do not have an assignment currently'
      redirect_to root_path and return
    end

    @translation = Translation.find(params[:translation_id])

app/helpers/sentences_helper.rb
module SentencesHelper
  def top_edit_class(top)
    if top == 'M'
      'top-edit-majority'
    elsif top == 'T'
      'top-edit-tie'
    elsif top == 'Z'
      'top-edit-zero-votes'
    else
      ''
    end
  end

  def voted_for(cur_edit)
    cur_edit.contributions.joins(assignment: :user).where(contributions: {kind: 'V'}, users: {username: current_user.username}).length > 0
  end

  def created(cur_edit)
    cur_edit.contributions.joins(assignment: :user).where(contributions: {kind: 'C'}, users: {username: current_user.username}).length > 0
  end

end

app/views/sentences/edit.html.erb
<h1 align='center'>Editing Sentence</h1>

<%= render 'form' %>

app/views/sentences/index.html.erb
<h1 align='center'>Sentences</h1>
<div class='container'>
  <div align='center'>
    <%= will_paginate @sentences %>
  </div>
  <table class='table table-condensed table-bordered table-hover'>
    <thead>
      <tr>
        <th>Blk</th>
        <th>Sub</th>
        <th>RSub</th>
        <th>Sen</th>
        <th>RSen</th>
        <th>Typ</th>
        <th>Tie</th>
        <th>Translation</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @sentences.each do |sentence| %>
        <tr>
          <td><%= sentence.blk %></td>
          <td><%= sentence.sub %></td>
          <td><%= sentence.rsub %></td>
          <td><%= sentence.sen %></td>
          <td><%= sentence.rsen %></td>
          <td><%= sentence.typ %></td>
          <td><%= sentence.tie %></td>
          <td><%= sentence.translation %></td>
          <td><%= link_to 'Show', [@translation, sentence] %></td>
          <td><%= link_to 'Edit', edit_translation_sentence_path(@translation, sentence) %></td>
          <td><%= link_to 'Destroy', [@translation, sentence], method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div align='center'>
    <%= will_paginate @sentences %>
  </div>
<div>
  

app/views/sentences/new.html.erb
<h1 align='center'>New Sentence</h1>

<%= render 'form' %>

app/views/sentences/show.html.erb
<% javascript_include_tag "content_edit" %>

<!-- timeout for inactivity to stop accumulating time in vote and create counters -->
<%= javascript_tag do %>
  var timeout_delay = <%= Contribution.cutoff*1000 %>; //in milli-seconds
  var timeout_location = "<%= timeout_sentence_url %>";
  var timeoutHandle = window.setTimeout(function() { window.location = timeout_location; }, timeout_delay);
  //setTimeout(function() { window.location = "http://www.google.com"; }, timeout_delay);
<% end %>

<div class='container'>
  <div align='center'>
      <%= form_tag({ :controller=>"sentences", :action=>"multi_button_action" }, method: :get, class: "form-inline") do %>
	      <%= link_to '', prev_sentence_path(translation_id: @translation.id, id: @sentence.id), class: 'btn btn-info btn-default glyphicon glyphicon-chevron-left', title: 'previous sentence', 'data-toggle'=>'tooltip', 'data-placement'=>'bottom', 'data-delay'=>'{"show": 2000, "hide": 100}' %>
        <%= link_to '', decrease_context_sentence_path(translation_id: @translation.id, id: @sentence.id), class: 'btn btn-warning btn-default glyphicon glyphicon-minus', title: 'decrease context', 'data-toggle'=>'tooltip', 'data-placement'=>'bottom' %>&nbsp;&nbsp;
	<%="(#{@sentence.id})" if current_user.admin? %>
<% if current_user.admin? %>
        <%= text_field_tag :blk, "#{@sentence.blk}", id: 'blk', class: 'form-control', placeholder: 'Blk', size: 3, title: 'current blk', 'data-toggle'=>'tooltip', 'data-placement'=>'bottom' %>
	<%="#{@sentence.sub}"%>
        <%= text_field_tag :rsub, "#{@sentence.rsub}", id: 'rsub', class: 'form-control', placeholder: 'RSub', size: 4, title: 'current rsub', 'data-toggle'=>'tooltip', 'data-placement'=>'bottom' %>
	<%="#{@sentence.sen}"%>
<% end %>
<%= text_field_tag :rsen, "#{@sentence.rsen}", id: 'rsen', class: 'form-control', placeholder: 'RSen', size: 4, title: 'current sentence', 'data-toggle'=>'tooltip', 'data-placement'=>'bottom' %>
<% if current_user.admin? %>
	<%="#{@sentence.typ}"%>
<% end %>
	<%= hidden_field_tag :translation_id, "#{@translation.id}" %>
	<%= button_tag('go', type: 'submit', class: "btn", :name => 'go_button', title: 'jump to sentence entered on the left', 'data-toggle'=>'tooltip', 'data-placement'=>'bottom') do %>
          <i class="btn btn-info btn-default glyphicon glyphicon-forward"></i>
        <% end %>
<% votes = current_user.cur_assign.contributions.where(kind: 'V').count if current_user.cur_assign %>
<% sens = @translation.sentences.count %>
        <%= votes %>/<%= sens %>
<% if sens > 0 %>
	<b><%= '%.1f' % ((votes/sens.to_f)*100) if votes %>%</b>
<% else %>
        <%= 'N/A' %>
<% end %>
<% if current_user.admin? %>
        <%= sentence_vote_time(@sentence) %>s
        <%= sentence_create_time(@sentence) %>s
<% end %>
        <%= text_field_tag :search_term, "#{session[:search_term]}", id: 'search_term', class: 'form-control', placeholder: 'Search', size: 7, title: 'enter search text', 'data-toggle'=>'tooltip', 'data-placement'=>'bottom' %>
	<%= button_tag('search', type: 'submit', class: "btn", :name => 'search_button', title: 'search for text entered on the left', 'data-toggle'=>'tooltip', 'data-placement'=>'bottom') do %>
          <i class="btn btn-success btn-default glyphicon glyphicon-search"></i>
        <% end %>
	<%= button_tag('place', type: 'submit', class: "btn", :name => 'place_button', title: 'return to your place in the document', 'data-toggle'=>'tooltip', 'data-placement'=>'bottom') do %>
          <i class="btn btn-info btn-default glyphicon glyphicon-bookmark"></i>
        <% end %>
	<%= button_tag('preview', type: 'submit', class: "btn", :name => 'preview_button', title: 'preview of previous 20 sentences up to your current sentence', 'data-toggle'=>'tooltip', 'data-placement'=>'bottom') do %>
          <i class="btn btn-primary btn-default glyphicon glyphicon-eye-open"></i>
        <% end %>
        <%= link_to '', increase_context_sentence_path(translation_id: @translation.id, id: @sentence.id), class: 'btn btn-warning btn-default glyphicon glyphicon-plus', title: 'increase context', 'data-toggle'=>'tooltip', 'data-placement'=>'bottom' %>
	<%= link_to '', next_sentence_path(translation_id: @translation.id, id: @sentence.id), class: 'btn btn-info btn-default glyphicon glyphicon-chevron-right', title: 'next sentence', 'data-toggle'=>'tooltip', 'data-placement'=>'bottom', 'data-delay'=>'{"show": 2000, "hide": 100}' %>
	<% end %>
  </div>

<% if current_user.admin? %>
  <div align='center' class='show-actions'>
    <%= link_to 'Edit', edit_translation_sentence_path(@translation, @sentence), class: 'btn btn-xs btn-primary' %>
    <%= link_to 'Delete', translation_sentence_path(@translation, @sentence), method: :delete, data: { confirm: 'Are you sure you want to delete the sentence?'}, class: 'btn btn-xs btn-danger' %>
    <%= link_to 'View Sentences', translation_sentences_path, class: 'btn btn-xs btn-success' %>
    <%= link_to 'New Sentence', new_translation_sentence_path(@translation), class: 'btn btn-xs btn-primary' %>
    &nbsp;
    <%= link_to 'New Edit', new_sentence_edit_path(@sentence), class: 'btn btn-xs btn-primary' %>
  </div>
<% end %>

  <div class="row">
    <div class="col-xs-12">
<% @pred_E_edits.each do |e| %>
	<div style='color:blue;'><%= markdown(e.content) %></div>
<% end %>
    </div>
  </div>
  <br/>

  <div class="row">
    <!--<table class="table table-bordered table-hover">-->
    <table class="table table-borderless table-hover">
<% if false %>
      <thead>
        <tr>
          <th>Id</th>
	  <th><%= markdown(@E_edit.content) if @E_edit %></th>
	  <th>(<%=@sentence.id%>) Sentence: <%=@sentence.blk%>.<%=@sentence.sub%>.<%=@sentence.rsub%>.<%=@sentence.sen%>.<%=@sentence.rsen%>.<%=@sentence.typ%></th>
          <th>#</th>
          <th>Contributions</th>
        </tr>
      </thead>
<% end %>
      <tbody>
        <tr>
<% if current_user.admin? %>
	  <td><%= link_to @E_edit.id,  sentence_edit_path(@E_edit.sentence, @E_edit) if @E_edit %></td>
<% end %>
	  <td style='color:blue;'><%= markdown(@E_edit.content) if @E_edit %></td>
        </tr>
<% @sentence.edits.order('created_at desc').each do |edit| %>
  <% vote = false %>
  <% if edit.sentence.translation.lan != 'ENG' %> 
        <tr>

<% if current_user.admin? %>
          <td><%= link_to edit.id, sentence_edit_path(edit.sentence, edit) %></td>
<% end %>

	  <td class='<%= top_edit_class(edit.top) %>', dir="auto">
            <div class="editable" id= <%= "#{edit.id}" %> >
              <%= form_tag("/sentences/#{edit.sentence_id}/edits/#{edit.id}/save_modified_clone", :method=>'post', dir: 'auto') do %>
                <%= text_area_tag :content, "#{edit.content}", class: "text_area_tag", id: "t#{edit.id}", style: 'width:100%; height:100%; font-size:12px; border:none;', dir: 'auto' %>
                <%= submit_tag 'Save', class: "submit_tag btn btn-default", style: 'display: none;' %>
                <%= submit_tag 'Cancel', class: "cancel_tag btn btn-default", style: 'display: none;' %>
                <%= button_tag 'Clear', type: 'button', class: "clear_tag btn btn-default", id: "c#{edit.id}", style: 'display: none;' %>
                <%#= text_field_tag 'base', 'm', id: "h#{edit.id}" %> <!-- for debug -->
                <%= hidden_field_tag 'base', 'm', id: "h#{edit.id}" %>
              <% end %>
            </div>

            <div class="presentable" id= <%= "p#{edit.id}" %> >
              <%= markdown(edit.content) %>
            </div>

          </td>

          <td class="center">
    <%# if created(edit) %>
    <% if ['LA'].include? current_user.cur_assign.role %>
              <%= link_to '', sentence_edit_path(@sentence, edit), method: :delete, data: { confirm: 'Are you sure you want to delete the edit?'}, class: 'btn btn-danger btn-default glyphicon glyphicon-trash icon-white' %>
    <% else %>
              <%#= link_to '', sentence_edit_path(@sentence, edit), method: :delete, data: { confirm: 'Are you sure you want to delete the edit?'}, class: 'btn btn-danger btn-default glyphicon glyphicon-trash icon-white disabled' %>
    <% end %>
    <% if voted_for(edit) %>
	    <%= link_to '', vote_sentence_edit_path(@sentence, edit), method: :post, class: "btn btn-success btn-default glyphicon glyphicon-ok icon-white", autofocus: true, id: "focusvote" %>
    <% else %>
	    <%= link_to '', vote_sentence_edit_path(@sentence, edit), method: :post, class: "btn btn-success btn-default glyphicon glyphicon-unchecked icon-white", autofocus: true, id: "focusvote" %>
    <% end %>
    <% if edit.top != 'N' %>
              <%#= link_to '', sentence_edit_path(@sentence, edit), method: :delete, data: { confirm: 'Are you sure you want to delete the edit?'}, class: 'btn btn-warning btn-lg glyphicon glyphicon-trash icon-white' %>
    <% end %>
          </td>

<% if current_user.admin? || current_user.cur_assign.role == 'CE' %>
	  <td>
	    <%= pluralize(edit.vote_count, 'vote') %>
          </td>

	  <td>
    <% edit.contributions.each do |c| %>
      <% if c.kind == 'C' %>
	      <div style='color:red;'><%= "#{c.kind}(#{c.effort_in_seconds})-#{c.assignment.role}-#{c.assignment.user.username}, " %></div> 
      <% elsif c.kind =='V' %>
	      <%= "#{c.kind}(#{c.effort_in_seconds})-#{c.assignment.role}-#{c.assignment.user.username}, " %> 
      <% else %>
	    <div style='color:green;'><%= "#{c.kind}-#{c.assignment.role}-#{c.assignment.user.username}, " %></div> 
      <% end %>
    <% end %>
          </td>
<% end %>

<% if current_user.admin? %>
	  <td>
    <% edit.contributions.each do |c| %>
	    <%= "#{c.kind}#{c.base}-#{c.base_edit_id}, " if c.base && c.base_edit %>
    <% end %>
          </td>
<% end %>

        </tr>
  <% end %><!--if-->
<% end %><!--each-->
      </tbody>
    </table>
  </div> <!--row-->

  <div class="row">
    <div class="col-xs-12">
<% @succ_E_edits.each do |e| %>
  <div style='color:blue;'><%= markdown(e.content) %></div>
<% end %>
    </div>
  </div> <!--row-->

  </div>
</div>

app/views/sentences/show_preview.html.erb
<!--<h3 align='center'>Preview</h3>-->
<div class='container'>

  <!--<h4 align='center'>English sentences:</h4>-->
  <div class="row">
    <div class="col-xs-12">
      <div style='color:blue;'><%= simple_format(@preview_E) %></div> 
    </div>
  </div>

  <!--<h4 align='center'>Translated sentences:</h4>-->
  <div class="row">
    <div class="col-xs-12">
      <div style='color:black;'><%= simple_format(@preview_O) %></div> 
    </div>
  </div>

<div class='center'>
  <%= link_to "Back to Proofread View", {controller: "sentences", action: "multi_button_action", translation_id: @translation.id, place_button: ''}, class: 'btn btn-xlarge btn-lg btn-success btn-primary' %>
</div>